# Generated by Django 5.0.2 on 2024-02-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SampledSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
                ("artwork", models.URLField()),
                ("audio", models.URLField()),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SamplerSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
                ("artwork", models.URLField()),
                ("audio", models.URLField()),
                ("year", models.IntegerField()),
                ("clue_1", models.TextField()),
                ("clue_2", models.TextField()),
                ("clue_3", models.TextField()),
            ],
        ),
    ]
