# Generated by Django 5.0.2 on 2024-03-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sampledsong",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="samplersong",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
