# Generated by Django 5.0.2 on 2024-03-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0002_alter_sampledsong_id_alter_samplersong_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SongPost",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("sampler_title", models.CharField(max_length=100)),
                ("sampled_title", models.CharField(max_length=100)),
                ("sampler_artist", models.CharField(max_length=100)),
                ("sampled_artist", models.CharField(max_length=100)),
                ("sampler_artwork", models.URLField()),
                ("sampled_artwork", models.URLField()),
                ("sampler_audio", models.URLField()),
                ("sampled_audio", models.URLField()),
                ("sampler_year", models.IntegerField()),
                ("sampled_year", models.IntegerField()),
                ("clue_1", models.TextField()),
                ("clue_2", models.TextField()),
                ("clue_3", models.TextField()),
                ("post_date", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="SampledSong",
        ),
        migrations.DeleteModel(
            name="SamplerSong",
        ),
    ]
