# Generated by Django 5.0.2 on 2024-03-31 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0003_songpost_delete_sampledsong_delete_samplersong"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="songpost",
            name="clue_1",
        ),
        migrations.RemoveField(
            model_name="songpost",
            name="clue_2",
        ),
        migrations.RemoveField(
            model_name="songpost",
            name="clue_3",
        ),
    ]
