# Generated by Django 5.0.2 on 2024-03-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0004_remove_songpost_clue_1_remove_songpost_clue_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songpost",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
