# Generated by Django 5.0.2 on 2024-03-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0005_alter_songpost_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songpost",
            name="post_date",
            field=models.DateField(unique=True),
        ),
    ]
