# Generated by Django 4.2 on 2024-05-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0002_delete_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("audio_file", models.FileField(upload_to="audio_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampled_album",
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampled_artist",
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampled_title",
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampler_album",
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampler_artist",
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampler_title",
            field=models.CharField(max_length=900),
        ),
    ]
