# Generated by Django 4.2 on 2024-05-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0003_audiofile_alter_songpost_sampled_album_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songpost",
            name="sampled_album",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampled_artist",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampled_title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampler_album",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampler_artist",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampler_title",
            field=models.CharField(max_length=100),
        ),
    ]
