# Generated by Django 4.2 on 2024-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0004_alter_songpost_sampled_album_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiofile",
            name="audio_file",
            field=models.BinaryField(),
        ),
    ]
