# Generated by Django 4.2 on 2024-05-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0006_alter_audiofile_audio_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songpost",
            name="sampled_album",
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampled_artist",
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampled_title",
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampler_album",
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampler_artist",
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampler_audio",
            field=models.URLField(max_length=900),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampler_title",
            field=models.CharField(max_length=900),
        ),
    ]
