# Generated by Django 4.2 on 2024-05-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0007_alter_songpost_sampled_album_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songpost",
            name="sampled_audio",
            field=models.URLField(max_length=900),
        ),
    ]
