# Generated by Django 4.2 on 2024-05-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0008_alter_songpost_sampled_audio"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AudioFile",
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampled_album",
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampled_artist",
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampled_artwork",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampled_audio",
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampled_year",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampler_audio",
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name="songpost",
            name="sampler_year",
            field=models.CharField(),
        ),
    ]
