# Generated by Django 4.2 on 2024-05-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0009_delete_audiofile_alter_songpost_sampled_album_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="songpost",
            name="sampled_audio_youtube_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="songpost",
            name="sampler_audio_start_time",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="songpost",
            name="sampler_audio_youtube_link",
            field=models.URLField(blank=True),
        ),
    ]
