# Generated by Django 5.0.2 on 2024-04-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0006_alter_songpost_post_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="songpost",
            name="sampled_album",
            field=models.CharField(default="value", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="songpost",
            name="sampler_album",
            field=models.CharField(default="value", max_length=100),
            preserve_default=False,
        ),
    ]
